/** @type {import('tailwindcss').Config} */
export default {
    theme: {
        extend: {
            colors: {
                "primary": "#0060ad",
                "primary-dim": "#005498",
                "primary-fixed": "#68abff",
                "primary-fixed-dim": "#599ef1",
                "primary-container": "#68abff",
                "on-primary": "#f8f8ff",
                "on-primary-container": "#002b52",
                "surface": "#f7f9fb",
                "surface-bright": "#f7f9fb",
                "surface-container-lowest": "#ffffff",
                "surface-container-low": "#f0f4f7",
                "surface-container": "#eaeff2",
                "surface-container-high": "#e3e9ed",
                "surface-container-highest": "#dce4e8",
                "surface-variant": "#dce4e8",
                "surface-tint": "#0060ad",
                "on-surface": "#2c3437",
                "on-surface-variant": "#596064",
                "on-background": "#2c3437",
                "secondary": "#4b626e",
                "secondary-dim": "#3f5661",
                "secondary-container": "#cde6f4",
                "secondary-fixed-dim": "#bfd8e5",
                "on-secondary": "#f2faff",
                "on-secondary-container": "#3e5560",
                "on-secondary-fixed-variant": "#475f6a",
                "tertiary": "#5f5a84",
                "tertiary-dim": "#534e77",
                "tertiary-container": "#d3ccfd",
                "tertiary-fixed-dim": "#c5beee",
                "on-tertiary": "#fcf7ff",
                "on-tertiary-container": "#47426b",
                "error": "#a83836",
                "error-dim": "#67040d",
                "error-container": "#fa746f",
                "on-error": "#fff7f6",
                "on-error-container": "#6e0a12",
                "outline": "#747c80",
                "outline-variant": "#acb3b7",
            },
            fontFamily: {
                "headline": ["Manrope", "sans-serif"],
                "body": ["Manrope", "sans-serif"],
                "label": ["Manrope", "sans-serif"],
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.75rem",
                "2xl": "1rem",
                "3xl": "1.5rem",
                "full": "9999px",
            },
        },
    },
}